config/routes.rb
FryFarmsCoop::Application.routes.draw do

  devise_for :users

  resources :pages, :only => [:index, :show]
  resources :orders

  match 'user_root', :to => "pages#show", :id => 'dashboard'

  namespace :admin do
    root :to => 'users#index'
    resources :users
    resources :vendors do
      resources :categories, :only => [:new]
    end
    resources :categories, :except => [:new, :index] do
      resources :items, :only => [:new]
    end
    resources :items, :except => [:index]
    resources :batches do
      match 'orders', :to => 'orders#index'
    end
    resources :orders, :only => [:show]
  end

  namespace :member do
    resources :orders
  end

  root :to => 'pages#index'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :orders
  belongs_to :pickup

  default_scope order('id DESC')

  scope :after_today, lambda {
    where("deadline IS NULL OR deadline > ?", Time.zone.now).
    order('deadline DESC')
  }

  scope :pickup, lambda { |pickup_id|
    where(:pickup_id => pickup_id)
  }

  # # If a date is entered, make sure it's not in the past
  validates_date :deadline,
                 :on_or_after => :today,
                 :on_or_after_message => "can't be a date in the past",
                 :if => lambda { |b| b.deadline.present? }

  # # Make sure there's only one Batch with an empty date for the pickup
  validates_date :deadline,
                 :allow_blank => false,
                 :invalid_date_message => "cannot be blank. There's already an order batch for this pickup location with a blank deadline.",
                 :if => lambda { |b| b.deadline.blank? && Batch.pickup(b.pickup_id).where("deadline IS NULL").size > 0 }

  validates_presence_of :pickup

  def self.current(pickup_id)
    # Carry forward manager notes from the last batch
    pickup(pickup_id).after_today.last || create!(:pickup_id => pickup_id, :manager_notes => most_recent(pickup_id).try(:manager_notes))
  end

  def self.most_recent(pickup_id)
    pickup(pickup_id).first
  end

end

app/controllers/admin/batches_controller.rb
class Admin::BatchesController < AdminController
  def index
    @batches = Batch.all.paginate :page => params[:page]
  end

  def show
    @batch = Batch.find(params[:id])
    @vendors = Vendor.all
  end

  def new
    @batch = Batch.new(:deadline => 7.days.from_now)
  end

  def create
    @batch = Batch.new(params[:batch])
    if @batch.save
      flash[:notice] = "Successfully added a new order batch"
      redirect_to admin_batches_path
    else
      render :new
    end
  end

  def edit
    @batch = Batch.find(params[:id])
  end

  def update
    @batch = Batch.find(params[:id])
    if @batch.update_attributes params[:batch]
      flash[:notice] = "Successfully updated order batch"
      redirect_to admin_batches_path
    else
      render :edit
    end
  end

  def destroy
    @batch = Batch.find(params[:id])
    if @batch.orders.size == 0 && @batch.destroy
      flash[:notice] = "Successfully deleted order batch"
    else
      flash[:error] = "Could not delete that batch"
    end
    redirect_to admin_batches_path
  end
end

app/views/admin/batches/_form.html.erb
<%= form_for [:admin, @batch] do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>

  <div class="field">
    <%= f.label :manager_notes, "Manager notes for this pickup location" %><br />
    <%= f.text_area :manager_notes, :cols => 80, :rows => 8 %>
  <br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/batches/edit.html.erb
<% title "Edit '#{@batch.pickup.name}' order batch" %>

<%= render 'form' %>

app/views/admin/batches/index.html.erb
<% title "Order batches" %>

<table>
  <thead>
    <tr>
      <th>Batch ID</th>
      <th>Pickup Location</th>
      <th>Deadline</th>
      <th>Orders</th>
      <%= content_tag :th, 'Options', { :colspan => 4, :style => 'text-align: center;' } if is_admin? %>
    </tr>
  </thead>
  <% @batches.each do |batch| %>
    <%= content_tag :tr, :class => cycle(nil, 'alt') do %>
      <td><%= batch.id %></td>
      <td><%= batch.pickup.name %></td>
      <th><%= link_to (batch.deadline ? batch.deadline.to_s(:table) : 'no deadline'), admin_batch_path(batch) %></th>
      <td><%= batch.orders.size %></td>
      <td><%= link_to "Summary", admin_batch_path(batch) %></td>
      <td><%= link_to "Orders", admin_batch_orders_path(batch.id) %></td>
      <td><%= link_to "Edit", edit_admin_batch_path(batch) %></td>
      <td><%= batch.orders.size > 0 ?
              '' :
              link_to("Delete", admin_batch_path(batch), :confirm => 'Are you sure?', :method => :delete) %></td>
    <% end %>
  <% end %>
</table>

<p><%= will_paginate @batches %></p>

<p><%= link_to "New order batch", new_admin_batch_path %></p>

app/views/admin/batches/new.html.erb
<% title "New order batch" %>

<%= render 'form' %>

<p><%= link_to "Cancel", admin_batches_path %></p>

app/views/admin/batches/show.html.erb
<% title "#{@batch.pickup.name} order (Batch #{@batch.id})" %>

<h3><%= "Order deadline: #{@batch.deadline ? @batch.deadline.to_s(:pretty) : 'none set'}" %></h3>

<%= simple_format(@batch.manager_notes) %>

<table>
  <% @vendors.each do |v| %>
    <tr>
      <td colspan="5">
        <div class="vendor">
          <h2><%= v.name %></h2>
        </div>
      </td>
    </tr>
    <% v.categories.each do |c| %>
      <% category_output = false %>
      <% c.items.by_name.each do |item| %>
        <% qty = @batch.orders.collect { |o| o.line_items.select { |i| i.item_id == item.id } }.flatten.inject(0) { |sum, line_item| sum + line_item.quantity } %>
        <% next if qty == 0 %>
        <% if !category_output %>
          <tr>
            <td>&nbsp;</td>
            <td colspan="4">
              <div class="category">
                <h3><%= c.name %></h3>
                <%= content_tag(:p, c.notes) if c.notes.present? %>
              </div>
            </td>
          </tr>
          <% category_output = true %>
        <% end %>
        <tr>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td><%= qty %> <%= item.sold_per %></td>
          <td>
            <%= item.name %><br />
            <span style="font-size: 11px; color: red;"><%= " (Limited availability)" if item.is_limited? %></span>
            <span style="font-size: 11px;"><%= "(#{item.notes})" if item.notes.present? %></span>
          </td>
          <td><%= item.price.to_currency %>/<%= item.uom %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>

  <tr>
    <td colspan="5">
      <div class="vendor">
        <h2>Customer Order Notes</h2>
        <% @batch.orders.by_user_name.each do |order| %>
          <% if order.notes.present? %>
            <h4><%= order.user.full_name %> (Order #<%= order.id %>)</h4>
            <%= simple_format order.notes %>
          <% end %>
        <% end %>
      </div>
    </td>
  </tr>
</table>