config/routes.rb
FryFarmsCoop::Application.routes.draw do

  devise_for :users

  resources :pages, :only => [:index, :show]
  resources :orders

  match 'user_root', :to => "pages#show", :id => 'dashboard'

  namespace :admin do
    root :to => 'users#index'
    resources :users
    resources :vendors do
      resources :categories, :only => [:new]
    end
    resources :categories, :except => [:new, :index] do
      resources :items, :only => [:new]
    end
    resources :items, :except => [:index]
    resources :batches do
      match 'orders', :to => 'orders#index'
    end
    resources :orders, :only => [:show]
  end

  namespace :member do
    resources :orders
  end

  root :to => 'pages#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :vendor
  has_many :items

  default_scope order('sequence ASC')
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    vendor = Vendor.find(params[:vendor_id])
    @category = Category.new(:vendor => vendor)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to admin_vendor_path(@category.vendor), :notice => 'Category was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to admin_vendor_path(@category.vendor), :notice => 'Category was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_vendor_path(@category.vendor)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<% title "Category for #{@category.vendor.name}" %>
<%= form_for [:admin, @category] do |f| %>
  <%= f.hidden_field :vendor_id %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sequence %><br />
    <%= f.text_field :sequence %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes, :rows => 4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render 'form' %>

<p><%= link_to 'Cancel', admin_vendor_path(@category.vendor) %></p>

app/views/admin/categories/new.html.erb
<%= render 'form' %>

<p><%= link_to 'Cancel', admin_vendor_path(@category.vendor) %></p>

app/views/admin/categories/show.html.erb
<% title "#{@category.name} from #{@category.vendor.name}" %>

<p><%= @category.notes %></p>

<p><%= link_to "Edit '#{@category.name}' category", edit_admin_category_path(@category) %></p>

<table>
  <thead>
    <tr>
      <th>Items</th>
      <th>Sold Per</th>
      <th>Price</th>
      <th>Available?</th>
      <th>Limited?</th>
      <th>Seasonal?</th>
      <%= content_tag :th, 'Options', { :colspan => 2, :style => 'text-align: center;' } %>
    </tr>
  </thead>
  <% @category.items.each do |item| %>
    <%= content_tag :tr, :class => cycle(nil, 'alt') do %>
      <th><%= item.name %></br><span style="font-size:8pt; font-weight: normal;"><%= item.notes %></span></th>
      <td><%= item.sold_per %></td>
      <td class="price-column"><%= "#{item.price.to_currency}/#{item.uom}" %></td>
      <td><%= red_green item.is_stocked?, 'In stock', 'Out of stock' %></td>
      <td><%= red_green !item.is_limited?, '', 'Limited' %></td>
      <td><%= red_green !item.is_seasonal?, '', 'Seasonal' %></td>
      <td><%= link_to 'Edit', edit_admin_item_path(item) %></td>
      <td>
        <% if item.line_items.empty? %>
          <%= link_to 'Delete', admin_item_path(item), :confirm => 'Are you sure?', :method => :delete %>
        <% else %>
          In Use
        <% end %>
      </td>
    <% end %>
  <% end %>
  <tr>
    <td colspan="7">
      <%= link_to "New '#{@category.name}' item", new_admin_category_item_path(@category) %>
    </td>
  </tr>
</table>

<p><%= link_to "View all #{@category.vendor.name} categories", admin_vendor_path(@category.vendor)  %></p>