config/routes.rb
FryFarmsCoop::Application.routes.draw do

  devise_for :users

  resources :pages, :only => [:index, :show]
  resources :orders

  match 'user_root', :to => "pages#show", :id => 'dashboard'

  namespace :admin do
    root :to => 'users#index'
    resources :users
    resources :vendors do
      resources :categories, :only => [:new]
    end
    resources :categories, :except => [:new, :index] do
      resources :items, :only => [:new]
    end
    resources :items, :except => [:index]
    resources :batches do
      match 'orders', :to => 'orders#index'
    end
    resources :orders, :only => [:show]
  end

  namespace :member do
    resources :orders
  end

  root :to => 'pages#index'
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :categories

  default_scope order('sequence ASC')
end

app/controllers/admin/vendors_controller.rb
class Admin::VendorsController < AdminController
  def index
    @vendors = Vendor.all
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def new
    @vendor = Vendor.new
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def create
    @vendor = Vendor.new(params[:vendor])

    if @vendor.save
      redirect_to(admin_vendors_path, :notice => 'Vendor was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @vendor = Vendor.find(params[:id])

    if @vendor.update_attributes(params[:vendor])
      redirect_to(admin_vendors_path, :notice => 'Vendor was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    redirect_to(admin_vendors_path)
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/admin/vendors/_form.html.erb
<%= form_for [:admin, @vendor] do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sequence %><br />
    <%= f.text_field :sequence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/vendors/edit.html.erb
<% title "Editing #{@vendor.name}" %>

<%= render 'form' %>

<p><%= link_to 'Cancel', admin_vendors_path %></p>

app/views/admin/vendors/index.html.erb
<% title 'Listing vendors' %>
<p>(click the vendor's name to edit products)</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <%= content_tag :th, 'Options', { :colspan => 2, :style => 'text-align: center;' } %>
    </tr>
  </thead>
  <% @vendors.each do |vendor| %>
    <%= content_tag :tr, :class => cycle(nil, 'alt') do %>
      <th><%= link_to vendor.name, admin_vendor_path(vendor) %></th>
      <td><%= link_to 'Edit', edit_admin_vendor_path(vendor) %></td>
      <td>
        <% if vendor.categories.empty? %>
          <%= link_to 'Delete', admin_vendor_path(vendor), :confirm => 'Are you sure?', :method => :delete %></td>
        <% else %>
          Has Categories
        <% end %>
    <% end %>
  <% end %>
  <tr>
    <td colspan="3">
      <%= link_to 'New Vendor', new_admin_vendor_path %>
    </td>
  </tr>
</table>

app/views/admin/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<p><%= link_to 'Cancel', admin_vendors_path %></p>

app/views/admin/vendors/show.html.erb
<% title @vendor.name %>
<p>(click a category name to edit products)</p>
<table>
  <thead>
    <tr>
      <th>Categories</th>
      <%= content_tag :th, 'Options', { :colspan => 2, :style => 'text-align: center;' } %>
    </tr>
  </thead>
  <% @vendor.categories.each do |category| %>
    <% row_class = cycle(nil, 'alt') %>
    <%= content_tag :tr, :class => row_class do %>
      <th><%= link_to category.name, admin_category_path(category) %></th>
      <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
    <% end %>
    <%= content_tag :tr, :class => row_class do %>
      <td colspan="3"><%= category.notes %></td>
    <% end %>
  <% end %>
  <tr>
    <td colspan="3">
      <%= link_to 'New category', new_admin_vendor_category_path(@vendor) %>
    </td>
  </tr>
</table>