config/routes.rb
FryFarmsCoop::Application.routes.draw do

  devise_for :users

  resources :pages, :only => [:index, :show]
  resources :orders

  match 'user_root', :to => "pages#show", :id => 'dashboard'

  namespace :admin do
    root :to => 'users#index'
    resources :users
    resources :vendors do
      resources :categories, :only => [:new]
    end
    resources :categories, :except => [:new, :index] do
      resources :items, :only => [:new]
    end
    resources :items, :except => [:index]
    resources :batches do
      match 'orders', :to => 'orders#index'
    end
    resources :orders, :only => [:show]
  end

  namespace :member do
    resources :orders
  end

  root :to => 'pages#index'
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_orders.html.erb
<p><%= will_paginate orders if orders.respond_to?(:total_pages) %></p>

<table style="width: 100%;">
  <thead>
    <tr>
      <th>Date</th>
      <th>Qty</th>
      <th>Name</th>
      <th>Price</th>
      <th>Farm</th>
    </tr>
  </thead>
  <% orders.each do |order| %>
    <% row_class = cycle(nil, 'alt') %>
    <%= content_tag :tr, :class => row_class do %>
      <td colspan="5">
        <h2>Order #<%= order.id %></h2>
        <%= content_tag('h3', link_to(order.user.full_name, admin_user_path(order.user)) + " / #{order.user.email}") if is_admin? %>
        <p>Received <%= order.created_at.to_s(:pretty) %></p>
        <% if order.notes.present? %>
          <p>Notes: <%= order.notes %></p>
        <% end %>
      </td>
    <% end %>
    <% order.line_items.each do |line_item| %>
      <%= content_tag :tr, :class => row_class do %>
        <td>&nbsp;</td>
        <td><%= line_item.quantity %> <%= line_item.sold_per %></td>
        <td>
          <%= line_item.name %><br />
          <span style="font-size: 11px; color: red;"><%= " (Limited availability)" if line_item.is_limited %></span>
          <span style="font-size: 11px;"><%= "(#{line_item.notes})" if line_item.notes.present? %></span>
        </td>
        <td>
          <%= line_item.price.to_currency %>/<%= line_item.uom %>
        </td>
        <td><%= line_item.vendor_name %></td>
      <% end %>
    <% end %>
  <% end %>
</table>

<p><%= will_paginate orders if orders.respond_to?(:total_pages) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? "#{yield(:title)} :: Fry Farms Coop" : "Fry Farms Coop" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body id="<%= body_id %>">
    <div id="container">
      <div id="navigation">
        <div id="public-nav">
          <ul>
            <%= content_tag :li, link_to('Home', user_signed_in? ? user_root_path : root_path, :class => 'home') %>
            <% if !user_signed_in? %>
              <%= content_tag :li, link_to('About Us', page_path('about'), :class => 'about') if false %>
              <%= content_tag :li, link_to('Join',     page_path('join'),  :class => 'join') %>
            <% else %>
              <%= content_tag :li, link_to('Your Orders', member_orders_path,  :class => 'orders') %>
              <%= content_tag :li, link_to('FAQ',         page_path('faq'),    :class => 'faq') %>
            <% end %>
            <% if is_admin? %>
              <%= content_tag :li, link_to('Members', admin_users_path,   :class => 'users') %>
              <%= content_tag :li, link_to('Farms/Items', admin_vendors_path, :class => 'vendors') %>
              <%= content_tag :li, link_to('Order Summaries', admin_batches_path, :class => 'order_summary') %>
            <% end %>
          </ul>
        </div>
        <div id="user-nav">
          <% if user_signed_in? %>
            Welcome, <%= current_user.first_name %>.
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Members: Sign in and place orders", new_user_session_path if body_id != 'sessions-new' %>
          <% end %>
        </div>
      </div>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
    <div class="legal">
      <p>© Copyright 2011 - <%= Time.now.year -%>, Tim Harvey. All rights reserved.</p>
    </div>

    <div class="disclaimer">
      <p>Since the families who participate in the Fry Farms Co-Op are Amish, they cannot run a web site. This site is<br />
      owned and managed by Tim Harvey, of Mountain View, CA (formerly Fort Wayne, IN), as a volunteer service to the Fry Farms Co-op.</p>
    </div>

    <div class="help">
      <p>For help with ordering or questions about the farm, contact <%= link_to Manager.full_name, "mailto:#{Manager.email}" %>, Co-op Managers. <br />Contact <%= link_to 'Tim Harvey', 'mailto:tim@literacy5.com' %> if you have technical difficulties with the site.</p>
    </div>
  </body>
</html>